### PR TITLE
[#84] Beautify -h (4×' ', 15×opt, desc)

### PR DESCRIPTION
**Pull request by pickfire**
Finally, my first pull request. Hope you'll like it.

### CODE REVIEW

**Comment by bucaran** [comment]
Thanks @pickfire! But it seems you forgot to update tests.

**Comment by bucaran** [comment]
To fix tests just,

```fish
fisher help --commands=bare | fisher help --usage > $fisher_home/test/fixtures/help/usage.txt
```

**Comment by bucaran** [comment]
@pickfire Do you realize you can just push force to this branch to update it?

**Comment by pickfire** [comment]
@bucaran, yeah, I have some trouble working on it, I am actually using another directory for the development, not `~/.local/share/fisherman`.

**Comment by pickfire** [comment]
Oh, now it's even bad, I have deleted the fisherman's whole directory.

**Comment by bucaran** [comment]
Your changes were perfect, the only thing that needed update was one test case :confused:

**Comment by pickfire** [comment]
Okay, I am currently reviving it by **undo** *manually*.

**Pull request closed without merging**
