### PR TITLE
Fix broken config.fish symlinks during install

### PR DESCRIPTION
**Pull request by aristidesfl**
Credits to @tuvistavie
https://github.com/fisherman/fisherman/issues/16#issuecomment-201699699

closes 16

### CODE REVIEW

**Comment by bucaran** [comment]
@aristidesfl I'd like to merge this, but can you share if this worked out for you when you tried it?

**Comment by aristidesfl** [comment]
Yes it works. Wouldn't submit otherwise :)



On Wed, Apr 13, 2016 at 14:58, Jorge Bucaran <notifications@github.com> wrote:
@aristidesfl [https://github.com/aristidesfl] I'd like to merge this, but can you share if this worked out for you when you tried it?

**Comment by bucaran** [comment]
I think I deserve that answer, thanks @aristidesfl!

**Comment by aristidesfl** [comment]
Better safe then sorry :+1:

**Pull request merged**
