### PR TITLE
add 2.0.0 Chinese README.md

### PR DESCRIPTION
**Pull request by detailyang**
ping @bucaran

### CODE REVIEW

**Comment by bucaran** [comment]
@detailyang Cool, would you mind adding?

```
fisherman is a zero-configuration, concurrent plugin manager for the fish shell.

Read this document in another language: Español, 日本語, 简体中文.


```

**Comment by detailyang** [comment]
wait a minute:)

**Comment by detailyang** [comment]
ping @bucaran

**Comment by bucaran** [comment]
Sweet!!!

**Comment by fishequality** [comment]
@detailyang One last tiny bit, in the Chinese translation we should not link to the Chinese translation right? Rather point back to the English one.

**Comment by detailyang** [comment]
agree with you, we should link to English one

**Pull request merged**
