### PR TITLE
Add FAQ for resolving github api token issues

### PR DESCRIPTION
**Pull request by ianferguson**
Add a FAQ section for how to resolve ls-remote being rate limited/rejected by the GitHub api when accessing anonymously.

### CODE REVIEW

**Comment by brj** [comment]
LGTM!

**Comment by ianferguson** [comment]
I'm on a different computer this morning and trying to reproduce the root issue (just to double check that the instructions I put work end to end) and am not actually able to get it to reproduce, even when I run `while true; fisher ls-remote; end` for a few minutes.

I'm going to look into this a little more over the weekend, but probably shouldn't merge this until its clear that the origin issue in #312 is _actually_ an issue, sorry!

**Comment by brj** [comment]
Sounds reasonable. I'll assign you to this issue then. Merge when you are ready please :)

**Comment by brj** [comment]
@ianferguson Okay, so here's the thing. I knew that many unauthenticated requests to the GitHub API would quickly reach the limit, so no matter how many times you run ls-remote, fisherman will only update the index once every 30 minutes IIRC. That's what may be happening here, thus you can't repro it again.

**Comment by ianferguson** [comment]
@brj good flag! I should have time either a bit later today, or tomorrow to set up a repro that induces the GitHub api limit without using fisher ls-remote in that case. Probably overkill at this point, but just want to make sure I cross my t's and dot my i's before merging.

**Comment by ianferguson** [comment]
Just confirmed that once GitHub's search api is rejecting anonymous requests, following the instructions in this PR will resolve the issue.

**Comment by brj** [comment]
Thanks and welcome aboard :)

**Pull request merged**
