### PR TITLE
Add missed files

### PR DESCRIPTION
**Pull request by sijad**

### CODE REVIEW

**Comment by detailyang** [comment]
LGTM ping @bucaran

**Comment by bucaran** [comment]
@sijad Can you just push the .gitignore for now. I am not sure we should keep using .editorconfig and the reason is that there is a `fish_indent` function that can help us format the code similar to what `go fmt` does for golang.

For this we would need to create a simple plugin to wrap the function, but it would be nice to have.

Please tell me if that has nothing to do with .editorconfig or if I missed something.

**Comment by sijad** [comment]
done ;-)

**Comment by sijad** [comment]
let me change the commit message

**Comment by sijad** [comment]
good to go

**Pull request merged**
