### PR TITLE
Updated Russian docs for v2.2.0

### PR DESCRIPTION
**Pull request by laughedelic**
Just reflected the changes in a70d48b. And did some minor rewording.

@demidovakatya, @denji, any other russian-speakers
you're welcome to review 😉

### CODE REVIEW

**Comment by bucaran** [comment]
Thanks @laughedelic.

Feel free to merge. I'll push your other recommendations later with a patch for ls-remote.

**Comment by bucaran** [comment]
LGTM

**Comment by laughedelic** [comment]
I'd like to update it to the current state of the readme first.

**Comment by bucaran** [comment]
Thanks, I already fixed the broken link.

**Pull request merged**
