### PR TITLE
[#129] Beautify man pages

### PR DESCRIPTION
**Pull request by pickfire**
Sorry for the late commit, I don't have the time to read through all the docs, I just skim though it and fix everything quickly.

### CODE REVIEW

**Comment by bucaran** [comment]
@pickfire Thanks so much! Mind you, I will end up merging some of these documents later and simplifying even more, but this should

**Comment by bucaran** [comment]
@pickfire I merged locally and will push with your commits later today. Please don't add anything else here.

You are free to take this on after I merged the new docs. A lot of docs were removed and simplified into `fisher.1`.

**Comment by pickfire** [comment]
Ah, I am currently not working on fisherman, I don't have anything interested to do in fisherman except for the support of parallelism.

**Comment by bucaran** [comment]
@pickfire Sure, give that a shot. I would love to see what some benchmark results.

**Comment by pickfire** [comment]
@bucaran, I didn't do any benchmarks, I can even feel that it is slower (my eyes and brain) so it must means that there is about one or two seconds slower for `parallel`.

**Comment by bucaran** [comment]
So, why is the point of implementing a feature that is slower?

**Comment by pickfire** [comment]
That's why I am asking for your opinion, whether `xargs` or `parallel`. I suggest `xargs` for this.

**Comment by bucaran** [comment]
I say `xargs` too.

**Comment by pickfire** [comment]
@bucaran Okay, now I am thinking about adding it to fisherman, give me some time.

**Pull request merged**
