### PR TITLE
Explain `ls-remote --format` option

### PR DESCRIPTION
**Pull request by asymmetric**
Add example of using `ls-remote --format` to display additional info about available plugins.

### CODE REVIEW

**Comment by jbucaran** [comment]
@asymmetric Thanks!!

**Comment by edouard-lopez** [comment]
Thanks @asymmetric 
@jbucaran updated the French version.

I just noticed this by chance, is there a way to keep translation update? First would be to tag such issues/PR as `translation`-related.

**Comment by jbucaran** [comment]
@edouard-lopez

>  Is there a way to keep translation update?

Tough one. We could ping the previous translators, but still.

BTW I just created a _translation_ tag. Please use it accordingly!

**Comment by edouard-lopez** [comment]
@jbucaran I can't set labels, you [need `Write permissions` or `Admin permissions`](https://help.github.com/articles/repository-permission-levels-for-an-organization/) to do so.

**Comment by jbucaran** [comment]
@edouard-lopez Fixed that for everyone!

**Pull request merged**
