### PR TITLE
Document how to install branches and tags

### PR DESCRIPTION
**Pull request by aristidesfl**
Closes: #364

### CODE REVIEW

**Comment by jbucaran** [comment]
Nice gesture adding it to the man page too. Do you think it would sound more natural to say:

> Install by tag.
>Install by branch name.

I'm not sure.

**Comment by aristidesfl** [comment]
I would say no, but up to you. @laughedelic ?

Related: https://medium.com/dropbox-design/design-words-with-data-fe3c525994e7#.k3uxwqkbo

**Comment by jbucaran** [comment]
Nice link. Okay, let's go with what you wrote. @laughedelic's feedback would also be appreciated.

**Comment by laughedelic** [comment]
I think it's better the way @aristidesfl wrote it 👌

- "... by ..." sounds for me like "by the means of ...", which is not applicable. You _refer_ to what you want to install by a tag/branch, but you install by... I don't know, running this command, using fisherman...
- "install from tag" just sounds strange to me. A tag is rather a fixed point in time, while here is feels like a location/place/source.

I'm not a native English speaker though 😅

**Comment by jbucaran** [comment]
@aristidesfl lgtm

**Comment by jbucaran** [comment]
Thank you @laughedelic.

**Pull request merged**
