### PR TITLE
sync with english README.md

### PR DESCRIPTION
**Pull request by detailyang**

### CODE REVIEW

**Comment by bucaran** [comment]
@detailyang What's up?

**Comment by detailyang** [comment]
just keep sync with your master branch README.md:)

**Comment by bucaran** [comment]
Yeah, why did you close it?

**Comment by detailyang** [comment]
nope, i did not  close it :(

**Comment by bucaran** [comment]
I am not sure what happened here.

**Comment by bucaran** [comment]
Can you fix the conflicts and push again?

**Comment by detailyang** [comment]
okay , let me try

**Comment by detailyang** [comment]
hey, this PR is merged to branch 1.5.0. So i will close this PR and send a PR to master again

**Pull request closed without merging**
