### PR TITLE
update Chinese README.md

### PR DESCRIPTION
**Pull request by detailyang**

### CODE REVIEW

**Comment by detailyang** [comment]
ping @bucaran  update Chinese README.md and remove something about npm

**Comment by bucaran** [comment]
@detailyang LGTM

**Comment by detailyang** [comment]
we should remove `npm un -g fisherman` in English README.md

**Comment by bucaran** [comment]
Will do.

**Comment by detailyang** [comment]
now i merged by myself?  :smile:

**Comment by bucaran** [comment]
Yeah.

**Pull request merged**
